import re

# Hang time and arc shape
PEAK_BIAS = 0.65         
BOUNCE_HEIGHT_MULT = 6
JUMP_HEIGHT_SCALE = 0.6

# Frame constants
PRE_CONTACT_OFFSET = 1
TOTAL_FRAMES = 250
CONTACT_EPSILON = -0.62
APEX_BACK_BLEND = 0.65

# Squash constants
SQUASH_FRAME_OFFSET  = 1
RECOVER_FRAME_OFFSET = 2
SQUASH_HOLD_FRAMES   = 2
SQUASH = 0.38

# Stretch constants
STRETCH_AT_PEAK = 0.0    
STRETCH_PRECONTACT_MULT = 1.0
STRETCH_RISE_MULT = 0.85
STRETCH = 0.40

# Tangent weights
APEX_TANGENT_WEIGHT = 14

# Rotation
VEL_NORMALIZER = 0.08
DIAG_ANGLE = 22.0 

# Regex
DIGIT_REGEX = re.compile(r"(\d+)$")